name: NetCoreUtils.Database

on:
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: change to NetCoreUtils.Database directory
      run: cd NetCoreUtils.Database\NetCoreUtils.Database
    - name: pack
      run: dotnet pack --configuration Release --output bin\Pack
    - name: view packed file
      run: cd bin\Pack && dir
    
