name: NetCoreUtils.Database

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version for the release (e.g., v1.0.0)'
        required: false
        default: 'latest'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: pack
      run: dotnet pack NetCoreUtils.Database\NetCoreUtils.Database\NetCoreUtils.Database.csproj --configuration Release --output bin/Pack
    - name: view packed file
      run: cd bin\Pack && dir
    - name:  Upload NuGet packages
      uses: actions/upload-artifact@v4
      with:
        name: nupkg-files
        path: bin/Pack/*.nupkg
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag_version }}
        release_name: "NetCoreUtils.Database ${{ github.event.inputs.tag_version }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
